yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'
         ),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/',
         views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'
         ),
    path('password_change/done/',
         views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_reset/',
         views.PasswordResetView.as_view(
             template_name='users/password_reset_form.html'
         ),
         name='password_reset'),
    path('password_reset/done/',
         views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('reset/done/',
         views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler500 = 'core.views.server_error'
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar

#     urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True,
        max_length=50
    )
    description = models.TextField()

    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Публикацию'
        verbose_name_plural = 'Публикации'


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комменты'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментирии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def paginator(request, post_list):
    post = Paginator(post_list, settings.AMOUNT_POSTS)
    page_number = request.GET.get('page')
    return post.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group')
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_count = author.posts.count()
    post_list = author.posts.select_related('author')
    page_obj = paginator(request, post_list)
    is_following = Follow.objects.filter(
        user=request.user,
        author=author,
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts_amount': posts_count,
        'is_following': is_following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.instance.author = request.user
        form.instance.post = form
        form.save()
        return redirect('posts:profile', form.instance.author)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if request.method != 'POST':
        return render(request, 'posts/post_create.html', {
            'form': form,
            'post': post
        })

    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})

    form.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/post_detail.html', {'form': form})

    form.instance.author = request.user
    form.instance.post = post
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_show = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, posts_show)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(user=request.user.id, author=author)
    if request.user != author and not is_following.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(user=request.user.id, author=author)
    if is_following.exists():
        is_following.delete()
    return redirect('posts:profile', username=username)

yatube/templates/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}    
        <div class="form-group mb-2">
          {% for field in form %}
          {{ form.text|addclass:"form-control" }}
          {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
        {% comment %} <a class="btn btn-primary" href="{% url 'posts:post_detail' post.pk %}">
          Отправить
        </a> {% endcomment %}
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/includes/footer.html
{% load static %}

<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© {{ year }} Copyright <span style="color: red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}  
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>      
</header>

yatube/templates/includes/post.html
{% load thumbnail %}

<ul>
  <li>
    Автор: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text|linebreaks|truncatewords:30 }}</p>
{% thumbnail post.image "800x600" crop="center" upscale=True as im %}
<img class="img-fluid" src="{{ im.url }}" width="550px">
{% endthumbnail %}<br>