yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler500 = 'core.views.server_error'
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar

#     urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True,
        max_length=50
    )
    description = models.TextField()

    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Публикацию'
        verbose_name_plural = 'Публикации'


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комменты'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментирии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def paginator(request, post_list):
    post = Paginator(post_list, settings.AMOUNT_POSTS)
    page_number = request.GET.get('page')
    return post.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group')
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_count = author.posts.count()
    post_list = author.posts.select_related('author')
    page_obj = paginator(request, post_list)
    is_following = Follow.objects.filter(
        user=request.user,
        author=author,
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts_amount': posts_count,
        'is_following': is_following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.instance.author = request.user
        form.instance.post = form
        form.save()
        return redirect('posts:profile', form.instance.author)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    if request.method != 'POST':
        return render(request, 'posts/post_create.html', {
            'form': form,
            'post': post
        })

    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})

    form.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/post_detail.html', {'form': form})

    form.instance.author = request.user
    form.instance.post = post
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_show = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, posts_show)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(user=request.user.id, author=author)
    if request.user != author and not is_following.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(user=request.user.id, author=author)
    if is_following.exists():
        is_following.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}
  Страница сообщества Yatube|Follow
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Последние обновления на странице Follow </h1>
      {% for post in page_obj %}
      {% include 'posts/includes/switcher.html' %}
        {% include 'includes/post.html' %}
        <a href="{% url 'posts:post_detail' post.pk %}">
        Подробная информация </a><br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a><br>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}
  Все записи группы {{ group }}
{% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block content %}
  <h3>
  <p>
  {{ group.description }}
  </p>
  </h3>
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    <a href="{% url 'posts:post_detail' post.pk %}">Пдробная информация </a><br>
    <a href="{% url 'posts:index' %}"> На главную</a>
    <hr>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}
  Страница сообщества Yatube
{% endblock %}

{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      <a href="{% url 'posts:post_detail' post.pk %}">
      Подробная информация </a><br>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a><br>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %}{% if post %} Редактировать запись {% else %} Новый пост{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}

<body>	   
  <main>
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if post %} Редактировать запись {% else %} Новый пост{% endif %}            
          </div>
          <div class="card-body">        
            <form method="POST" action="{% if post %} {% url 'posts:post_edit' form.instance.id %}{% else %}{% url 'posts:post_create' %}{% endif %}"  enctype="multipart/form-data" >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    {{ field.label }}
                    {% if field.field.required %}
                      *
                    {% endif %}
                  </label>
                  {{ field }}
                  {{ field.help_text }}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}
                    Редактировать запись
                  {% else %}
                    Добавить
                  {% endif %}               
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Пост{% endblock %}
{% block content %}
<head>
  <style>
  </style>
</head>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group in post %}
        <li class="list-group-item">
          Группа: {{ post.group }}<br>
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:index' %}"> На главную</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "1400x1050" crop="center" upscale=True as im %}
        <img class="img-fluid" src="{{ im.url }}" width="750px" height="{{ im.height }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      {% if request.user == post.author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        Редактировать запись
      </a>
      {% endif %}
      {% include 'includes/comment.html' %}
    </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %} Профайл пользователя {{ author }} {% endblock %}
{% block content %}
<h1>Все посты пользователя {{ author.get_full_name }}</h1>
<h3>Всего постов: {{ author.posts.count }}</h3>
{% if is_following %}
<a
  class="btn btn-lg btn-light"
  href="{% url 'posts:profile_unfollow' author.username %}"
  role="button"
>
  Отписаться
</a>
{% else %}
<a
  class="btn btn-lg btn-primary"
  href="{% url 'posts:profile_follow' author.username %}"
  role="button"
>
  Подписаться
</a>
{% endif %} {% for post in page_obj %}
<article>
  <ul>
    <li>Автор: {{ post.author.get_full_name }}</li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  <p>{{ post.text|truncatewords:30 }}</p>
  <p>
    <a href="{% url 'posts:post_detail' post.pk %}">Пдробная информация </a>
  </p>
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a
  ><br />
  {% endif %}
  <a href="{% url 'posts:index' %}"> На главную</a>
  {% if not forloop.last %}
  <hr />
  {% endif %} {% endfor %} {% include 'posts/includes/paginator.html' %}
</article>

{% endblock %}